### ISSUE TITLE
Python 3.8 (pip) - no pre-built wheel package for kiwisolver 1.3.1

### ISSUE THREAD

**Issue by lbendezu** [nucleic/kiwi#102]
Hi guys,

I saw that this issue is pretty similar to this one --> https://github.com/nucleic/kiwi/issues/75

Can you please upload the wheels for 1.3.1 version (for python 3.8)?

Thank you very much!

**Comment by MatthieuDartiailh** [comment]
Wheel files are available for Python 3.8 for most systems (see https://pypi.org/project/kiwisolver/1.3.1/#files). Are you by chance running on Apple Silicon ? In this case it is not yet clear to me how to build wheel for this platform but I plan to investigate this issue soon.

**Comment by jimklo** [comment]
any update... Trying to install on NVIDIA Jetson (Jetpack 4.5.3 w/ Python 3.8).  `kiwisolver-1.3.1-cp38-cp38-manylinux2014_aarch64.whl` and building from source fails.

**Comment by MatthieuDartiailh** [comment]
What problem are you encountering exactly ? I am not familiar with NVIDIA Jetson. The only possible missing wheels at the moment are the ones for Apple Silicon I expect all other platforms to be working, so could you open a new issue with more information about your system and specific issue.

**Comment by jmrnilsson** [comment]
I had to run with the --no-cache option since it seems kiwi 1.1.0, which I previously rolled back to probably satisfied any requirements by Matplotlib or perhaps in turn numpy. 

Here is the relevant parts of `requirements.txt`:

```requirements.txt
lxml==4.6.2
flake8==3.9.0
luigi==3.0.2
numpy==1.20.1
# kiwisolver==1.1.0
matplotlib==3.4.0
```

Here goes:
```
Collecting kiwisolver>=1.0.1 (from matplotlib==3.4.0->-r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/90/55/399ab9f2e171047d28933ae4b686d9382d17e6c09a01bead4a6f6b5038f4/kiwisolver-1.3.1.tar.gz (53kB)
     |████████████████████████████████| 61kB 518kB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/someuser/somerepo/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/pip-install-nuazn_cn/kiwisolver/setup.py'"'"'; __file__='"'"'/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/pip-install-nuazn_cn/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/pip-install-nuazn_cn/kiwisolver/
    Complete output (166 lines):
    warning: no files found matching '*.png' under directory 'docs/source'
    no previously-included directories found matching '.git'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'docs/build'
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 15, in run
        self.byte_compile(outfiles)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/install_lib.py", line 132, in byte_compile
        byte_compile(files, optimize=0,
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/util.py", line 466, in byte_compile
        compile(file, cfile, dfile)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/py_compile.py", line 157, in compile
        os.makedirs(dirname)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      [Previous line repeated 2 more times]
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
        mkdir(name, mode)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 310, in wrap
        path = self._remap_input(name, path, *args, **kw)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 452, in _remap_input
        self._violation(operation, os.path.realpath(path), *args, **kw)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('/Users/someuser§/Library/Caches/com.apple.python/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz/cppy-1.1.0/setup.py", line 15, in <module>
        # - py/kiwisolver.cpp
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('/Users/someuser/Library/Caches/com.apple.python/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz/cppy-1.1.0/setup.py", line 15, in <module>
        # - py/kiwisolver.cpp
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('/Users/someuser/Library/Caches/com.apple.python/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/pip-install-nuazn_cn/kiwisolver/setup.py", line 69, in <module>
        setup(
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/someuser/somerepo/.venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/Users/someuser/Library/Caches/com.apple.python/private/var/folders/3y/pkwnc9195872xxbbb6srlgg40000gn/T/easy_install-jknc96sz', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

-Best of luck!

**Comment by jimklo** [comment]
> What problem are you encountering exactly ? I am not familiar with NVIDIA Jetson. 

Basically imagine a Raspberry Pi 4 with 32 GB RAM and a big NVIDIA GPU running Ubuntu 18. (At times I think it's a $700 doorstop given the various NVIDIA Jetpack foo it forces one to deal with; like latest pre-built libs for anything Python being 3.6) I've installed Python 3.8 myself, along with CUDA 10.2, pytorch 1.7... go figure when trying to install pandas... which requires matplotlib, it fails on kiwisolver... 

Basically it should run `aarch64` Linux binaries without much problem. 

> The only possible missing wheels at the moment are the ones for Apple Silicon I expect all other platforms to be working, so could you open a new issue with more information about your system and specific issue.

I did eventually get it installed, but I think I had to manually install various dependencies, nevertheless lack of kiwisolver causes matplotlib to fail installation.  I can open another ticket; however it's odd that the wheel I referenced doesn't work... not sure where `manylinux` comes from, but pretty sure this is the problem as that doesn't match anything `uname` would return.

**Comment by MatthieuDartiailh** [comment]
Could you share the error message ? Also did you manage to install numpy for example ?

**Comment by PiotrKurnik** [comment]
> Wheel files are available for Python 3.8 for most systems (see https://pypi.org/project/kiwisolver/1.3.1/#files). Are you by chance running on Apple Silicon ? In this case it is not yet clear to me how to build wheel for this platform but I plan to investigate this issue soon.

Any thoughts on that one? Unfortunately that's my case.

**Comment by MatthieuDartiailh** [comment]
cibuildwheel has since added support for building wheels for the M1. Kiwi wheels are built at https://github.com/MacPython/kiwisolver-wheels and somebody provided a PR against main. But I forgot to backport it to  the most recent version currently on PyPI and publish the resulting wheels. I will do my best to get at it this week. Ping me if nothing happens.

**Comment by jmrnilsson** [comment]
This looks like something I had this on Intel inside MacBook Pro after upgrading to latest MacOS.

**Comment by MatthieuDartiailh** [comment]
I built the wheels but did not upload them to PyPI yet since I could not test them. They are available from anaconda.org and can be installed using `pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple kiwisolver` if anybody can confirm that the MacOS arm and universal2 wheels behave as expected it would be great.
