### ISSUE TITLE
Missing wheel dependency? Installation fails.

### ISSUE THREAD

**Issue by druzmieres** [nucleic/kiwi#123]
Hi, 

The installation fails for kiwisolver==1.2.0.

Python version: 3.9.7
pip version: 21.3.1
OS: MacOS Big Sur 11.5.2

I'm running the following commands to install the package:
```
# Create a directory and navigate to it
mkdir test
cd test
# Create and activate an environment
python3 -m venv .env
source .env/bin/activate
# Install requirements
pip install kiwisolver==1.2.0
```

I get the trace:
```
(.env) user@laptop test % pip install kiwisolver==1.2.0
Collecting kiwisolver==1.2.0
 Using cached kiwisolver-1.2.0.tar.gz (52 kB)
  ERROR: Command errored out with exit status 1:
   command: /home/user/test/.env/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-install-5t3yrtzv/kiwisolver_64a781d3f6fd40898c8349740ba48fc4/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-install-5t3yrtzv/kiwisolver_64a781d3f6fd40898c8349740ba48fc4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-pip-egg-info-beaf5nod
     cwd: /private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-install-5t3yrtzv/kiwisolver_64a781d3f6fd40898c8349740ba48fc4/
  Complete output (44 lines):
  WARNING: The wheel package is not available.
   ERROR: Command errored out with exit status 1:
    command: /home/user/test/.env/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-wheel-5jmlnfcc/cppy_b72905edd312431891cc2aa8fb5bd5b7/setup.py'"'"'; __file__='"'"'/private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-wheel-5jmlnfcc/cppy_b72905edd312431891cc2aa8fb5bd5b7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-wheel-e3daa8yx
      cwd: /private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-wheel-5jmlnfcc/cppy_b72905edd312431891cc2aa8fb5bd5b7/
   Complete output (6 lines):
   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
   error: invalid command 'bdist_wheel'
   ----------------------------------------
   ERROR: Failed building wheel for cppy
  ERROR: Failed to build one or more wheels
  Traceback (most recent call last):
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
    subprocess.check_call(cmd)
   File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/user/test/.env/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/tmpoyzho1sb', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
  The above exception was the direct cause of the following exception:
  Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/private/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/pip-install-5t3yrtzv/kiwisolver_64a781d3f6fd40898c8349740ba48fc4/setup.py", line 59, in <module>
    setup(
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
   File "/home/user/test/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
   File "/home/user/test/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
   File "/home/user/test/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
    return fetch_build_egg(self, req)
   File "/home/user/test/.env/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
    raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/home/user/test/.env/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/7p/2s9w2pmx4rv88d3t63fgq8gw0000gn/T/tmpoyzho1sb', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/62/b8/db619d97819afb52a3ff5ff6ad3f7de408cc83a8ec2dfb31a1731c0a97c2/kiwisolver-1.2.0.tar.gz#sha256=247800260cd38160c362d211dcaf4ed0f7816afb5efe56544748b21d6ad6d17f (from https://pypi.org/simple/kiwisolver/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement kiwisolver==1.2.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2)
ERROR: No matching distribution found for kiwisolver==1.2.0
```

If I install wheel manually first, the installation of kiwisolver succeeds, but installing wheel first wasn't required for Python versions 3.6 to 3.8 (and the default pip versions associated to them).

**Comment by SauravMaheshkar** [comment]
This seems like a `virtualenv` / `PYTHONPATH` error rather than a `kiwisolver` error. @druzmieres can you confirm if the issue still persists ?

**Comment by MatthieuDartiailh** [comment]
Pip now always build a wheel when installing a project from source. However kiwi itself does not need wheel (python.py install just works). I plan to add PEP 517 support soon which should definitively fix this problem.

However I am curious why do you need to install from 1.2 from source ? 1.3.1 has pre-built wheels for Linux, Mac and Windows on x86-64, aarch64, ppc64le and s390x.

**Comment by MatthieuDartiailh** [comment]
Closing for lack of feedback
