### ISSUE TITLE
#egg=kiwisolver See assertion error when installing kiwisolver

### ISSUE THREAD

**Issue by rudo7802** [nucleic/kiwi#159]
Here is the error message when I tried to install kiwisolver using pip3, thank you!

Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4.tar.gz (97 kB)
     |████████████████████████████████| 97 kB 12.2 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  WARNING: Generating metadata for package kiwisolver produced metadata for project name unknown. Fix your #egg=kiwisolver fragments.
ERROR: Exception:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 425, in _resolve_one
    assert req_to_install.user_supplied
AssertionError

**Comment by rudo7802** [comment]
Hello folks, When I tried to install kiwisolver using pip3, I encountered this error. It would be very nice if you could help me look into that. Thank you!

**Comment by MatthieuDartiailh** [comment]
I am surprised to see pip trying to install from source. Can you share your MacOS version and pip version ?

**Comment by rudo7802** [comment]
This issue is solved by update pip.

**Comment by rudo7802** [comment]
Thank you for getting back.
