### ISSUE TITLE
install: cannot change permissions of ‘/usr/bin’: Operation not permitted

### ISSUE THREAD

**Issue by burlen** [nucleic/kiwi#74]
The install step for the `tools` target is ignoring `--prefix` and going to `/usr`. This fails when installing into a Python that is not located there. Also while `/usr` is a fine default prefix, `usr` should not always be part of the prefix.

### The error:
```bash
install: cannot change permissions of ‘/usr/bin’: Operation not permitted
make[4]: *** [Makefile:17: install] Error 1
make[3]: *** [Makefile:45: install] Error 2
Traceback (most recent call last):
  File "setup.py", line 221, in <module>
    setup(**config)
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 170, in run
    subprocess.check_output(command).decode(),
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['make', 'python_version=3', 'tools', 'install']' returned non-zero exit status 2.
```

### how to reproduce:
```bash
env CC=/usr/lib64/ccache/cc CXX=/usr/lib64/ccache/c++ \
    CPPFLAGS="-I/home/bloring/work/teca/TECA_superbuild/install/include" CFLAGS="-I/home/bloring/work/teca/TECA_superbuild/install/include  -O3 -march=native -mtune=native -DNDEBUG" \
    CXXFLAGS="-I/home/bloring/work/teca/TECA_superbuild/install/include  -O3 -march=native -mtune=native -DNDEBUG" \
    LDFLAGS="-L//home/bloring/work/teca/TECA_superbuild/install/lib -L/home/bloring/work/teca/TECA_superbuild/install/lib64" \
    LD_LIBRARY_PATH=/home/bloring/work/teca/TECA_superbuild/install/lib/:/home/bloring/work/teca/TECA_superbuild/install/lib64/: \
    DYLD_LIBRARY_PATH=/home/bloring/work/teca/TECA_superbuild/install/lib/:/home/bloring/work/teca/TECA_superbuild/install/lib64/: \
    PKG_CONFIG_PATH=/home/bloring/work/teca/TECA_superbuild/install/lib/pkgconfig:/home/bloring/work/teca/TECA_superbuild/install/lib64/pkgconfig: \
    PATH=.:/home/bloring/work/teca/TECA_superbuild/install/bin/:/usr/libexec/python3-sphinx:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/bloring/.local/bin:/home/bloring/bin \
    PYTHONHOME=/home/bloring/work/teca/TECA_superbuild/install \
    MPLBACKEND=Agg \
    PYTHONPATH=/home/bloring/work/teca/TECA_superbuild/install/lib:/home/bloring/work/teca/TECA_superbuild/install/lib/python3.7/site-packages/  \
    /home/bloring/work/teca/TECA_superbuild/install/bin/python3 setup.py build install --prefix=/home/bloring/work/teca/TECA_superbuild/install
```
we are building and installing a full stack of all of our project's dependencies. we install everything in arbitarry location specified by the user. environment variables setup the environment (as shown here). we are installing kiwi because it is a dependence of matplotlib.

### The problem
It seems that the command line that make's the target `tools`, doesn't override the variable `buildroot`. 

from top level Makefile
```bash
 21 .PHONY: tools
 22 tools:
 23     # apart from all python source we need to compile the
 24     # C tools. see setup.py for details when this target is
 25     # called
 26     ${MAKE} -C tools all
```
I think you could pass `buildroot=${buildroot}` on line 26?

Also, it looks weird to me that you are installing things to `${buildroot}/usr`.  From `tools/Makefile`
```bash
 16 install:
 17     install -d -m 755 ${buildroot}usr/bin
 18     install -m 755 $(PRGS) ${buildroot}usr/bin 
```
It is unusual to force `usr` into the install prefix. It will probably cause us problems even if the install succeeded. The more standard way would be to put stuff in `${buildroot}/bin`  and `${buildroot}/lib`, and make `buildroot` default to `/usr/` instead of hard coding `usr` into all the paths.

**Comment by MatthieuDartiailh** [comment]
Not sure what I can do about this. Kiwisolver does not have a Makefile and simply relies on setuptools. Where did you find the makefile you are referencing ?

**Comment by burlen** [comment]
I got the files from PyPi...aha! there is another project named kiwi! 

https://pypi.org/project/kiwi/#files

since your project is called kiwisolver, it's a little confusing that your github is named kiwi. That said, this issue is with the other kiwi project (which I do not need). 

Sorry for my confusion!
