### ISSUE TITLE
Matplotlib installation failing because of kiwisolver broken wheel

### ISSUE THREAD

**Issue by SarvagyaVaish** [nucleic/kiwi#95]
Edit: See [this comment](https://github.com/nucleic/kiwi/issues/95#issuecomment-719034822) below for fix. 

----

Getting the following error when installing matplotlib on EB instance. We got around it by explicitly specifying the version in  requirements.txt
```
kiwisolver==1.2.0
```

Error:
```
    ----------------------------------------
    Failed building wheel for kiwisolver
    Running setup.py clean for kiwisolver
  Failed to build kiwisolver
  Installing collected packages: kiwisolver, matplotlib, docopt, termcolor, pick, webcolors, pyopenssl, pyasn1, ndg-httpsclient, pynacl, bcrypt, paramiko, decorator, datadog, nodeenv, toml, aspy.yaml, identify, virtualenv, cfgv, zipp, importlib-resources, importlib-metadata, pre-commit, progress, sqlparse, django, django-environ, whitenoise, django-braces, django-crispy-forms, django-floppyforms, future, django-json-widget, django-model-utils, defusedxml, python3-openid, oauthlib, requests-oauthlib, django-allauth, psycopg2, unidecode, unicode-slugify, django-autoslug, django-timezone-field, redis, django-redis, click, rq, django-rq, billiard, vine, amqp, kombu, celery, djangorestframework, django-annoying, django-quicky, ptyprocess, pexpect, django-simple-history, phonenumberslite, django-phonenumber-field, qrcode, django-otp, django-formtools, django-two-factor-auth, django-decorator-include, django-ses, django-fixture-magic, django-enumfields, django-ratelimit, django-admin-multiple-choice-list-filter, django-ipware, txaio, autobahn, zope.interface, hyperlink, Automat, PyHamcrest, incremental, constantly, pyasn1-modules, service-identity, twisted, asgiref, daphne, channels, hiredis, async-timeout, aioredis, msgpack, channels-redis, greenlet, gevent, ua-parser, user-agents, django-user-agents, pluggy, py, wcwidth, atomicwrites, more-itertools, pytest, pytest-django, pytest-asyncio, django-extensions, django-test-plus, django-debug-toolbar, anyjson, python-utils, django-utils2, django-admin-generator, django-debug-panel, phonenumbers, freezegun, transitions, websocket-client, ecdsa, rsa, python-jose, marshmallow, coverage, alabaster, sphinxcontrib-serializinghtml, MarkupSafe, Jinja2, snowballstemmer, imagesize, sphinxcontrib-qthelp, sphinxcontrib-jsmath, Pygments, sphinxcontrib-applehelp, sphinxcontrib-devhelp, sphinxcontrib-htmlhelp, Sphinx, Werkzeug, text-unidecode, Faker, factory-boy, pytest-sugar, simplejson, ws4py, recordclass, progressbar, python-lzf, netifaces, joblib, scikit-learn, pandas, seaborn, pip, nose, mock, psutil, ddtrace, frecency
    Running setup.py install for kiwisolver: started
      Running setup.py install for kiwisolver: finished with status 'error'
      Complete output from command /opt/python/run/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5uopv2_g/kiwisolver/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-hvc07yzh-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python3.6/kiwisolver:
      running install
      running build
      running build_ext
      building 'kiwisolver' extension
      creating build
      creating build/temp.linux-x86_64-3.6
      creating build/temp.linux-x86_64-3.6/py
      gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-5uopv2_g/kiwisolver/.eggs/cppy-1.1.0-py3.6.egg/cppy/include -I. -I/usr/include/python3.6m -c py/kiwisolver.cpp -o build/temp.linux-x86_64-3.6/py/kiwisolver.o -std=c++11
      gcc: error trying to exec 'cc1plus': execvp: No such file or directory
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  Command "/opt/python/run/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5uopv2_g/kiwisolver/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-hvc07yzh-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/python/run/venv/include/site/python3.6/kiwisolver" failed with error code 1 in /tmp/pip-build-5uopv2_g/kiwisolver/
  You are using pip version 9.0.1, however version 20.2.4 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2020-10-28 05:05:02,152 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)
```

**Comment by amaurymercier** [comment]
same issue here

**Comment by nephtyws** [comment]
Help

**Comment by MatthieuDartiailh** [comment]
Sorry but I have a hard time to follow. What OS and Python version are you seeing this issue ? From the error message it looks like you are trying to build from source as if the wheel was missing. Checking PyPI wheel are present for all version of Python that 1.2 supported. The Linux wheel use a more recent version of manylinux though.

For 1.0.1 please be more specific. This version only supports 2.7, 3.4 3.5 3.6 and 3.7.

**Comment by MatthieuDartiailh** [comment]
Actually looking a bit deeper you should update your pip version. You are using pip v9 when the current version is pip v20 and typically manylinux wheels 2010 require pip > 19.3. Given the pain building the wheels have been this time around I would prefer not building also wheels using the old and outdated manylinux1 format.

**Comment by SebastianB12** [comment]
I'm using the AWS Beanstalk environment with Python 3.6 running on 64bit Amazon Linux/2.9.15.
Deployment fails since a few hours with same error.
Using matplotlib==3.1.2

**Comment by MatthieuDartiailh** [comment]
As mentioned earlier upgrading pip should fix the issue. I am looking into making manylinux1 wheels again but some updates to the c++ codebase are preventing that build to complete at the moment.

**Comment by SebastianB12** [comment]
Thanks for the the hint. I upgraded the pip version. Don't know why Amazon is using such an old pip version. Now everything works again.
Here is how I updated Pip in Elastic Beanstalk: https://stackoverflow.com/a/42477724
Thanks!

**Comment by MatthieuDartiailh** [comment]
On CIs platform it can be a good idea to always update pip since they tend to use the system python with whatever pip version shipped at the time.

**Comment by raduslmn** [comment]
Suddenly one of our production cloud docker containers doesn't start anymore because we started getting this same error when it's trying to install `matplotlib`. 
Below you can find the Docker file content which reproduces the exact same error as described by the original post

```
FROM marketplace.gcr.io/google/ubuntu1804:latest

RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends 
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    vim.tiny wget sudo net-tools ca-certificates unzip \
	apt-transport-https python3.7 python3-pip \
    python3-setuptools 
RUN pip3 install matplotlib
 
```

**Comment by SarvagyaVaish** [comment]
We were able to fix the issue by

- forcing a pip version as part of the requirements.txt

```
pip==19.1.1
```

- adding an ebextension as follows

```
commands:
  pip_upgrade:
    command: /opt/python/run/venv/bin/pip install --upgrade pip
    ignoreErrors: false
```

**Comment by Qix-** [comment]
@SarvagyaVaish Don't put pip versions in library `requirements.txt` files. You can enforce `pip` versions in CI by specifying the version on the command line just like you did in your `requirements.txt`:

```
commands:
  pip_upgrade:
    command: /opt/python/run/venv/bin/pip install --upgrade pip==19.1.1
    ignoreErrors: false
```

The reason being is that, for those that do not have a virtualenv, you'll be **rolling back** their global version of `pip` if they are on a newer version; pip does not no-op package installations if they're an older version than what's already available, so they'll instead uninstall the newer version first and rollback, which is sure to upset others who have to work with your codebase.

Consider adding a note to your build/usage instructions about the requirement of `pip>=19.1.1` instead. Some people can't upgrade and thus might have to consider using another library instead of wasting a bunch of time rolling back `pip` due to a library mandating it.

**Comment by krzysiekmwk** [comment]
Hi, I described problem here: https://github.com/matplotlib/matplotlib/issues/18846

**Comment by MatthieuDartiailh** [comment]
That last problem is different and is not related to pip version. I tested on Anaconda (Python 3.6, 3.7, 3.8 and 3.9) where I could reproduce the failure, but not with python 3.9 installed with Windows. I will delete the Windows wheels for now till I can figure out the issue.

**Comment by MatthieuDartiailh** [comment]
If anybody can help me investigate the faulty wheel are still available from https://anaconda.org/multibuild-wheels-staging/kiwisolver/files and can be installed using the following command `pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple kiwisolver`

**Comment by MatthieuDartiailh** [comment]
This issue points to the right culprit https://github.com/joerick/cibuildwheel/issues/423 I will do my best to build teh wheels without requiring the most recent VS redistributable and re-upload wheels soon.

**Comment by riedgar-ms** [comment]
> I will delete the Windows wheels for now till I can figure out the issue.

@MatthieuDartiailh did you do this for the PyPI binaries as well? Our Windows builds have turned red because they're fetching the source tarball, rather than the precompiled binaries, and they fail to build `kiwisolver`. The machines should be running with Python 3.6 (although Python 3.9 did just get rolled out, and may be lurking around).

**Comment by MatthieuDartiailh** [comment]
I deleted all windows wheel in the hope that people installing on windows would get the 1.2.0 which works with the VC2014 redistributable. I did not touch the Linux macos wheel nor the source dist.

**Comment by riedgar-ms** [comment]
That's it. Our pip install is falling back on to `Downloading kiwisolver-1.3.0.tar.gz (54 kB)`

**Comment by MatthieuDartiailh** [comment]
My bad I will just yank the release this way pip will avoid it.

**Comment by riedgar-ms** [comment]
Thanks - `matplotlib` installs are working in our Windows pipelines again.

**Comment by awaizman1** [comment]
Hi @MatthieuDartiailh,

Issue still exists with python 3.6.8 (but not with python 3.7), don't know why python 3.6 doesn't ignore yanked 1.3 version.
Do u plan to upload windows whl soon?

```
C:\Users\awaizman101364>kiwi\Scripts\python.exe -m pip install kiwisolver
Collecting kiwisolver
  Downloading https://files.pythonhosted.org/packages/00/4a/02235aace8c1db66f708a7bdff0cf5b231fad7359a21551fcab1bff4c68d/kiwisolver-1.3.0.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 237kB/s
Installing collected packages: kiwisolver
  Running setup.py install for kiwisolver ... error
    Complete output from command C:\Users\awaizman101364\kiwi\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\AWAIZM~1\\AppData\\Local\\Temp\\pip-install-7gwdiork\\kiwisolver\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AWAIZM~1\AppData\Local\Temp\pip-record-9hq2ngop\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\awaizman101364\kiwi\include\site\python3.6\kiwisolver:
    running install
    running build
    running build_ext
    building 'kiwisolver' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "C:\Users\awaizman101364\kiwi\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\AWAIZM~1\\AppData\\Local\\Temp\\pip-install-7gwdiork\\kiwisolver\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AWAIZM~1\AppData\Local\Temp\pip-record-9hq2ngop\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\awaizman101364\kiwi\include\site\python3.6\kiwisolver" failed with error code 1 in C:\Users\AWAIZM~1\AppData\Local\Temp\pip-install-7gwdiork\kiwisolver\
You are using pip version 18.1, however version 20.3b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by Alejandro-FA** [comment]
Hi, I don't understand what's going on, but as far as I understand I have the same issue with **python 3.9.0 and pip 20.2.4** when trying to install matplotlib in a python venv on linux. I post this in case that it helps. If anyone knows a temporary workaround I would like to know it, thanks.

I've checked and the kiwisolver version that pip has tried to install is indeed 1.2.0:

    Using version 1.2.0 (newest of versions: 1.0.1, 1.1.0, 1.2.0, 1.3.0)

Here's the error that I got, extracted from the log file:

    2020-11-01T11:52:59,585   error: command '/usr/bin/gcc' failed with exit code 1
    2020-11-01T11:52:59,612   ERROR: Failed building wheel for matplotlib
    2020-11-01T11:52:59,613   Running setup.py clean for matplotlib
    2020-11-01T11:52:59,613   Running command '/home/user/folder/.venv/bin/python3' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_2q_y0d/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j_2q_y0d/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
    2020-11-01T11:52:59,836   running clean
    2020-11-01T11:52:59,837   removing 'build/temp.linux-x86_64-3.9' (and everything under it)
    2020-11-01T11:52:59,837   removing 'build/lib.linux-x86_64-3.9' (and everything under it)
    2020-11-01T11:52:59,844   'build/bdist.linux-x86_64' does not exist -- can't clean it
    2020-11-01T11:52:59,844   'build/scripts-3.9' does not exist -- can't clean it
    2020-11-01T11:52:59,860   Created temporary directory: /tmp/pip-wheel-fvtrz2dp
    2020-11-01T11:52:59,860   Destination directory: /tmp/pip-wheel-fvtrz2dp
    2020-11-01T11:52:59,860   Running command '/home/user/folder/.venv/bin/python3' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_2q_y0d/kiwisolver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j_2q_y0d/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fvtrz2dp
    2020-11-01T11:53:00,049   running bdist_wheel
    2020-11-01T11:53:00,049   running build
    2020-11-01T11:53:00,050   running build_ext
    2020-11-01T11:53:00,051   building 'kiwisolver' extension
    2020-11-01T11:53:00,051   creating build
    2020-11-01T11:53:00,051   creating build/temp.linux-x86_64-3.9
    2020-11-01T11:53:00,051   creating build/temp.linux-x86_64-3.9/py
    2020-11-01T11:53:00,051   gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-install-j_2q_y0d/kiwisolver/.eggs/cppy-1.1.0-py3.9.egg/cppy/include -I. -I/home/user/folder/.venv/include -I/usr/include/python3.9 -c py/constraint.cpp -o build/temp.linux-x86_64-3.9/py/constraint.o -std=c++11
    2020-11-01T11:53:00,086   In file included from /tmp/pip-install-j_2q_y0d/kiwisolver/.eggs/cppy-1.1.0-py3.9.egg/cppy/include/cppy/cppy.h:16,
    2020-11-01T11:53:00,086                    from py/constraint.cpp:10:
    2020-11-01T11:53:00,086   /tmp/pip-install-j_2q_y0d/kiwisolver/.eggs/cppy-1.1.0-py3.9.egg/cppy/include/cppy/defines.h:10:10: fatal error: Python.h: No such file or directory
    2020-11-01T11:53:00,086      10 | #include <Python.h>
    2020-11-01T11:53:00,086         |          ^~~~~~~~~~
    2020-11-01T11:53:00,086   compilation terminated.
    2020-11-01T11:53:00,088   error: command '/usr/bin/gcc' failed with exit code 1
    2020-11-01T11:53:00,104   ERROR: Failed building wheel for kiwisolver
    2020-11-01T11:53:00,104   Running setup.py clean for kiwisolver
    2020-11-01T11:53:00,104   Running command '/home/user/folder/.venv/bin/python3' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_2q_y0d/kiwisolver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j_2q_y0d/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
    2020-11-01T11:53:00,293   running clean
    2020-11-01T11:53:00,293   removing 'build/temp.linux-x86_64-3.9' (and everything under it)
    2020-11-01T11:53:00,293   'build/lib.linux-x86_64-3.9' does not exist -- can't clean it
    2020-11-01T11:53:00,293   'build/bdist.linux-x86_64' does not exist -- can't clean it
    2020-11-01T11:53:00,293   'build/scripts-3.9' does not exist -- can't clean it
    2020-11-01T11:53:00,293   removing 'build'
    2020-11-01T11:53:00,306 Failed to build matplotlib kiwisolver
    2020-11-01T11:53:00,394 Installing collected packages: certifi, cycler, kiwisolver, numpy, pyparsing, matplotlib

**Comment by MatthieuDartiailh** [comment]
I had to yank (mark as bad) the 1.3.0 release which added 3.9 support. I have good hope to release a fixed version either today or early this week.

**Comment by MatthieuDartiailh** [comment]
Kiwisolver v1.3.1 is now online for Python 3.6 to 3.9. Windows wheels link against VC2014 and not VC2014_1 and manylinux1 wheels which works with all version of pip are provided. Wheels for ARM, PPC64le and PyPy3.6 are also provided. Hopefully this fixes all the issues reported in the past week. Once again sorry for the inconvenience.

**Comment by piksel** [comment]
@MatthieuDartiailh Maybe you could mention why this was yanked on some relevant places? It took a good while to find this comment to explain why builds suddenly started failing (they used a a fixed `kiwisolver==1.3.0` requirement).

**Comment by MatthieuDartiailh** [comment]
PyPI should have at least a short comment about this. Not sure where to document this. Any suggestion ?

**Comment by piksel** [comment]
Hm, I didn't see anything on https://pypi.org/project/kiwisolver/1.3.0/ except `This release has been yanked`, but that's probably the ideal place. Second place I looked were the [release on github](https://github.com/nucleic/kiwi/releases/tag/1.3.0) (which is a bit... lacking in information overall 😁).
It's just nice to now that it was yanked because it might not run in certain environments, not because it contained a serious security flaw that might jeopardize your production servers etc. 😅
